#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>


typedef int8_t __int8;
typedef int16_t __int16;
typedef int32_t __int32;
typedef int64_t __int64;


typedef struct __attribute__((packed)) {
    __int8 CustomerRevision[32];
    __int8 BusRatio[8];
    __int8 D2KCreditConfig;
    __int8 SnoopThrottleConfig;
    __int8 LegacyVgaSoc;
    __int8 LegacyVgaStack;
    __int8 P2pRelaxedOrdering;
    __int8 DebugPrintLevel;
    __int8 NumaEn;
    __int8 SncEn;
    __int8 UmaClustering;
    __int8 IoDcMode;
    __int8 DegradePrecedence;
    __int8 Degrade4SPreference;
    __int8 DirectoryModeEn;
    __int8 XptPrefetchEn;
    __int8 KtiPrefetchEn;
    __int8 XptRemotePrefetchEn;
    __int8 KtiFpgaEnable[8];
    __int8 DdrtQosMode;
    __int8 KtiLinkSpeedMode;
    __int8 KtiLinkSpeed;
    __int8 KtiLinkL0pEn;
    __int8 KtiLinkL1En;
    __int8 KtiLinkSpeedPerPort[48];
    __int8 DfxL0pEnable[48];
    __int8 DfxL1Enable[48];
    __int8 KtiFailoverEn;
    __int8 KtiLbEn;
    __int8 KtiCrcMode;
    __int8 KtiCpuSktHotPlugEn;
    __int8 KtiCpuSktHotPlugTopology;
    __int8 KtiSkuMismatchCheck;
    __int8 TorThresLoctoremNorm;
    __int8 TorThresLoctoremEmpty;
    __int8 TscSyncEn;
    __int8 StaleAtoSOptEn;
    __int8 LLCDeadLineAlloc;
    __int8 MbeBWCalChoice;
    __int8 SplitLock;
    __int8 M2iosfToUpiAffinity;
    __int8 mmCfgBase;
    __int8 mmCfgSize;
    __int8 UnusedUpdSpace0[3];
    __int32 mmiohBase;
    __int8 CpuPaLimit;
    __int8 UnusedUpdSpace1;
    __int16 mmiohSize;
    __int8 isocEn;
    __int8 dcaEn;
    __int8 UnusedUpdSpace2[2];
    __int32 BoardTypeBitmask;
    __int32 AllLanesPtr;
    __int32 PerLanePtr;
    __int32 AllLanesSizeOfTable;
    __int32 PerLaneSizeOfTable;
    __int32 WaitTimeForPSBP;
    __int8 WaSerializationEn;
    __int8 KtiInEnableMktme;
    __int8 StackDisableBitMap[32];
    __int8 CFRS3mProvision;
    __int8 CFRS3mManualCommit;
    __int8 CFRPucodeProvision;
    __int8 CFRPucodeManualCommit;
    __int8 UnusedUpdSpace3[2];
    __int32 CFRImagePtr;
    __int8 VmxEnable;
    __int8 X2apic;
    __int8 ProcessorHyperThreadingDisable;
    __int8 ProcessorDynamicIssEnable;
    __int8 ProcessorLtsxEnable;
    __int8 HomelessPrefetchEnable;
    __int8 DdrFreqLimit;
    __int8 serialDebugMsgLvl;
    __int8 IioConfigIOU0[8];
    __int8 IioConfigIOU1[8];
    __int8 IioConfigIOU2[8];
    __int8 IioConfigIOU3[8];
    __int8 IioConfigIOU4[8];
    __int8 IioConfigIOU5[8];
    __int8 IioConfigIOU6[8];
    __int32 IioPcieConfigTablePtr;
    __int32 IioPcieConfigTableNumber;
    __int32 DeEmphasisPtr;
    __int32 DeEmphasisNumber;
    __int32 PcieCommonClockPtr;
    __int32 PcieCommonClockNumber;
    __int8 VtdSupport;
    __int8 VtdPciAcsCtlWaEn;
    __int8 UnusedUpdSpace4[2];
    __int32 PEXPHIDEPtr;
    __int32 PEXPHIDENumber;
    __int8 PcieHotPlugEnable;
    __int8 UnusedUpdSpace5;
    __int16 DelayAfterPCIeLinkTraining;
    __int32 PciBusResConfigPtr;
    __int32 PciBaseLimitsResConfigPtr;
    __int8 PchPciePllSsc;
    __int8 MeUmaEnable;
    __int8 SerialIoUartDebugEnable;
    __int8 UnusedUpdSpace6;
    __int16 SerialIoUartDebugIoBase;
    __int8 PanicWm;
    __int8 promoteMrcWarnings;
    __int8 promoteWarnings;
    __int8 serialDebugMsgLvlTrainResults;
    __int8 HwMemTest;
    __int8 UnusedUpdSpace7;
    __int16 MemTestLoops;
    __int8 UnusedUpdSpace8[2];
    __int32 AdvMemTestOptions;
    __int32 SmartTestKey;
    __int32 AdvMemTestCondPause;
    __int16 AdvMemTestCondTrefi;
    __int8 AdvMemTestCondTwr;
    __int8 UnusedUpdSpace9;
    __int16 AdvMemTestCondPmicVdd;
    __int8 AdvMemTestCondition;
    __int8 AdvMemTestResetList;
    __int8 MemTestOnColdFastBoot;
    __int8 AttemptFastBoot;
    __int8 AttemptFastBootCold;
    __int8 AllowedSocketsInParallel;
    __int8 AutoResetOnMemErr;
    __int8 EnableRMT;
    __int8 EnableRMTonFCB;
    __int8 JedecInitBeforeRMT;
    __int8 RMTBacksideMargining;
    __int8 RMTCmdAll;
    __int8 RMTDebugMessages;
    __int8 RMTDisplayTables;
    __int8 RMTLoopCount;
    __int8 UnusedUpdSpace10[3];
    __int32 TestSignalBitMaskRMT;
    __int8 RMTPerBitMargining;
    __int8 RMTPerCaLaneMargining;
    __int8 RMTPerDisplayPlots;
    __int8 RMTRxDqs;
    __int8 RMTRxVref;
    __int8 RMTScrambler;
    __int8 RMTStepSizeOverride;
    __int8 RMTTxDq;
    __int8 RMTTxVref;
    __int8 ErrorCheckScrub;
    __int8 EnforceDdrMemoryFreqPor;
    __int8 EnforcePopulationPor;
    __int8 pprType;
    __int8 ForcePprOnAllDramUce;
    __int8 UnusedUpdSpace11[2];
    __int32 PprAddrVariablePtr;
    __int8 allowCorrectableMemTestError;
    __int8 MemIOHealthCheck;
    __int8 CriticalRxDqsDelayLeftEdge;
    __int8 CriticalRxDqsDelayRightEdge;
    __int8 CriticalRxVrefLeftEdge;
    __int8 CriticalRxVrefRightEdge;
    __int8 CriticalTxDqDelayLeftEdge;
    __int8 CriticalTxDqDelayRightEdge;
    __int8 CriticalTxVrefLeftEdge;
    __int8 CriticalTxVrefRightEdge;
    __int8 MemIOHealthCriticalCaTimingLeftEdge;
    __int8 MemIOHealthCriticalCaTimingRightEdge;
    __int8 MemIOHealthCriticalCaVrefLeftEdge;
    __int8 MemIOHealthCriticalCaVrefRightEdge;
    __int8 ResetOnCriticalError;
    __int8 CriticalRetries;
    __int8 MemIOHealthLoopCount;
    __int8 TelemetryRxDqsDelayLeftEdge;
    __int8 TelemetryRxDqsDelayRightEdge;
    __int8 TelemetryRxVrefLeftEdge;
    __int8 TelemetryRxVrefRightEdge;
    __int8 TelemetryTxDqDelayLeftEdge;
    __int8 TelemetryTxDqDelayRightEdge;
    __int8 MemIOHealthTelemetryCaTimingLeftEdge;
    __int8 MemIOHealthTelemetryCaTimingRightEdge;
    __int8 MemIOHealthTelemetryCaVrefLeftEdge;
    __int8 MemIOHealthTelemetryCaVrefRightEdge;
    __int8 volMemMode;
    __int8 DynamicEccModeSel;
    __int8 PatrolScrub;
    __int8 PatrolScrubNotify;
    __int8 PatrolScrubDuration;
    __int8 PatrolScrubAddrMode;
    __int8 thermalthrottlingsupport;
    __int16 spareErrTh;
    __int8 WrCRC;
    __int8 AdaptiveRefreshMgmtLevel;
    __int8 MemHotIn;
    __int8 MemhotOutputOnlyOpt;
    __int8 DfxCxlType3LegacyEn;
    __int8 DfxPmicSecureMode;
    __int8 IioPcieSubSystemMode0[8];
    __int8 IioPcieSubSystemMode1[8];
    __int8 IioPcieSubSystemMode2[8];
    __int8 IioPcieSubSystemMode3[8];
    __int8 IioPcieSubSystemMode4[8];
    __int8 IioPcieSubSystemMode5[8];
    __int8 IioPcieSubSystemMode6[8];
    __int8 DfxCxlHeaderBypass;
    __int8 DfxCxlSecLvl;
    __int32 DfxCxlDebugModePtr;
    __int32 DfxCxlDebugModeNumber;
    __int8 LockChipset;
    __int8 ProcessorMsrLockControl;
    __int8 DFXEnable;
    __int8 DfxDisableBiosDone;
    __int8 CpuPmPackageCState;
    __int8 CpuPmEistEnable;
    __int8 CpuPmC1eEnable;
    __int8 CpuPmIssTdpLevel;
    __int8 CpuPmProcessorActivePbf;
    __int8 UnusedUpdSpace12[7];
    __int64 CpuPmCoreDisableBitmask0;
    __int64 CpuPmCoreDisableBitmask1;
    __int8 ReservedMemoryInitUpd[16];
} FSPM_CONFIG;

void display_fspm_conig(const FSPM_CONFIG *data);
void display_2_fspm_config(const FSPM_CONFIG *olddata, const FSPM_CONFIG *newdata); 


static void print_db_array(const __int8 *array, size_t size, const char *name) {

    printk(BIOS_SPEW,"DB ");
    for (size_t i = 0; i < size; i++) {
        printk(BIOS_SPEW, "0x%02X", (uint8_t)array[i]);
        if (i != size - 1) {
            printk(BIOS_SPEW, ", ");
        }
    }
    printk(BIOS_SPEW, " ; %s[%zu]\n", name, size);
}

static void print_db(__int8 value, const char *name) {
    printk(BIOS_SPEW, "DB 0x%02X ; %s\n", (uint8_t)value, name);
}

static void print_dw(__int16 value, const char *name) {
    printk(BIOS_SPEW, "DW 0x%04X ; %s\n", (uint16_t)value, name);
}

static void print_dd(__int32 value, const char *name) {
    printk(BIOS_SPEW, "DD 0x%08X ; %s\n", (uint32_t)value, name);
}

static void print_dq(__int64 value, const char *name) {
    printk(BIOS_SPEW, "DQ 0x%016llX ; %s\n", (unsigned long long)value, name);
}


void display_2_fspm_config(const FSPM_CONFIG *olddata, const FSPM_CONFIG *newdata) {
		printk(BIOS_SPEW, "\nOld FSPM_CONFIG\n");
		display_fspm_conig (olddata);
    printk(BIOS_SPEW, "New FSPM_CONFIG\n");
    display_fspm_conig (newdata);
		printk(BIOS_SPEW, "\n");
}

void display_fspm_conig(const FSPM_CONFIG *data) {
    // Process each member in order
    print_db_array(data->CustomerRevision, 32, "CustomerRevision");
    print_db_array(data->BusRatio, 8, "BusRatio");
    print_db(data->D2KCreditConfig, "D2KCreditConfig");
    print_db(data->SnoopThrottleConfig, "SnoopThrottleConfig");
    print_db(data->LegacyVgaSoc, "LegacyVgaSoc");
    print_db(data->LegacyVgaStack, "LegacyVgaStack");
    print_db(data->P2pRelaxedOrdering, "P2pRelaxedOrdering");
    print_db(data->DebugPrintLevel, "DebugPrintLevel");
    print_db(data->NumaEn, "NumaEn");
    print_db(data->SncEn, "SncEn");
    print_db(data->UmaClustering, "UmaClustering");
    print_db(data->IoDcMode, "IoDcMode");
    print_db(data->DegradePrecedence, "DegradePrecedence");
    print_db(data->Degrade4SPreference, "Degrade4SPreference");
    print_db(data->DirectoryModeEn, "DirectoryModeEn");
    print_db(data->XptPrefetchEn, "XptPrefetchEn");
    print_db(data->KtiPrefetchEn, "KtiPrefetchEn");
    print_db(data->XptRemotePrefetchEn, "XptRemotePrefetchEn");
    print_db_array(data->KtiFpgaEnable, 8, "KtiFpgaEnable");
    print_db(data->DdrtQosMode, "DdrtQosMode");
    print_db(data->KtiLinkSpeedMode, "KtiLinkSpeedMode");
    print_db(data->KtiLinkSpeed, "KtiLinkSpeed");
    print_db(data->KtiLinkL0pEn, "KtiLinkL0pEn");
    print_db(data->KtiLinkL1En, "KtiLinkL1En");
    print_db_array(data->KtiLinkSpeedPerPort, 48, "KtiLinkSpeedPerPort");
    print_db_array(data->DfxL0pEnable, 48, "DfxL0pEnable");
    print_db_array(data->DfxL1Enable, 48, "DfxL1Enable");
    print_db(data->KtiFailoverEn, "KtiFailoverEn");
    print_db(data->KtiLbEn, "KtiLbEn");
    print_db(data->KtiCrcMode, "KtiCrcMode");
    print_db(data->KtiCpuSktHotPlugEn, "KtiCpuSktHotPlugEn");
    print_db(data->KtiCpuSktHotPlugTopology, "KtiCpuSktHotPlugTopology");
    print_db(data->KtiSkuMismatchCheck, "KtiSkuMismatchCheck");
    print_db(data->TorThresLoctoremNorm, "TorThresLoctoremNorm");
    print_db(data->TorThresLoctoremEmpty, "TorThresLoctoremEmpty");
    print_db(data->TscSyncEn, "TscSyncEn");
    print_db(data->StaleAtoSOptEn, "StaleAtoSOptEn");
    print_db(data->LLCDeadLineAlloc, "LLCDeadLineAlloc");
    print_db(data->MbeBWCalChoice, "MbeBWCalChoice");
    print_db(data->SplitLock, "SplitLock");
    print_db(data->M2iosfToUpiAffinity, "M2iosfToUpiAffinity");
    print_db(data->mmCfgBase, "mmCfgBase");
    print_db(data->mmCfgSize, "mmCfgSize");
    print_db_array(data->UnusedUpdSpace0, 3, "UnusedUpdSpace0");
    print_dd(data->mmiohBase, "mmiohBase");
    print_db(data->CpuPaLimit, "CpuPaLimit");
    print_db(data->UnusedUpdSpace1, "UnusedUpdSpace1");
    print_dw(data->mmiohSize, "mmiohSize");
    print_db(data->isocEn, "isocEn");
    print_db(data->dcaEn, "dcaEn");
    print_db_array(data->UnusedUpdSpace2, 2, "UnusedUpdSpace2");
    print_dd(data->BoardTypeBitmask, "BoardTypeBitmask");
    print_dd(data->AllLanesPtr, "AllLanesPtr");
    print_dd(data->PerLanePtr, "PerLanePtr");
    print_dd(data->AllLanesSizeOfTable, "AllLanesSizeOfTable");
    print_dd(data->PerLaneSizeOfTable, "PerLaneSizeOfTable");
    print_dd(data->WaitTimeForPSBP, "WaitTimeForPSBP");
    print_db(data->WaSerializationEn, "WaSerializationEn");
    print_db(data->KtiInEnableMktme, "KtiInEnableMktme");
    print_db_array(data->StackDisableBitMap, 32, "StackDisableBitMap");
    print_db(data->CFRS3mProvision, "CFRS3mProvision");
    print_db(data->CFRS3mManualCommit, "CFRS3mManualCommit");
    print_db(data->CFRPucodeProvision, "CFRPucodeProvision");
    print_db(data->CFRPucodeManualCommit, "CFRPucodeManualCommit");
    print_db_array(data->UnusedUpdSpace3, 2, "UnusedUpdSpace3");
    print_dd(data->CFRImagePtr, "CFRImagePtr");
    print_db(data->VmxEnable, "VmxEnable");
    print_db(data->X2apic, "X2apic");
    print_db(data->ProcessorHyperThreadingDisable, "ProcessorHyperThreadingDisable");
    print_db(data->ProcessorDynamicIssEnable, "ProcessorDynamicIssEnable");
    print_db(data->ProcessorLtsxEnable, "ProcessorLtsxEnable");
    print_db(data->HomelessPrefetchEnable, "HomelessPrefetchEnable");
    print_db(data->DdrFreqLimit, "DdrFreqLimit");
    print_db(data->serialDebugMsgLvl, "serialDebugMsgLvl");
    print_db_array(data->IioConfigIOU0, 8, "IioConfigIOU0");
    print_db_array(data->IioConfigIOU1, 8, "IioConfigIOU1");
    print_db_array(data->IioConfigIOU2, 8, "IioConfigIOU2");
    print_db_array(data->IioConfigIOU3, 8, "IioConfigIOU3");
    print_db_array(data->IioConfigIOU4, 8, "IioConfigIOU4");
    print_db_array(data->IioConfigIOU5, 8, "IioConfigIOU5");
    print_db_array(data->IioConfigIOU6, 8, "IioConfigIOU6");
    print_dd(data->IioPcieConfigTablePtr, "IioPcieConfigTablePtr");
    print_dd(data->IioPcieConfigTableNumber, "IioPcieConfigTableNumber");
    print_dd(data->DeEmphasisPtr, "DeEmphasisPtr");
    print_dd(data->DeEmphasisNumber, "DeEmphasisNumber");
    print_dd(data->PcieCommonClockPtr, "PcieCommonClockPtr");
    print_dd(data->PcieCommonClockNumber, "PcieCommonClockNumber");
    print_db(data->VtdSupport, "VtdSupport");
    print_db(data->VtdPciAcsCtlWaEn, "VtdPciAcsCtlWaEn");
    print_db_array(data->UnusedUpdSpace4, 2, "UnusedUpdSpace4");
    print_dd(data->PEXPHIDEPtr, "PEXPHIDEPtr");
    print_dd(data->PEXPHIDENumber, "PEXPHIDENumber");
    print_db(data->PcieHotPlugEnable, "PcieHotPlugEnable");
    print_db(data->UnusedUpdSpace5, "UnusedUpdSpace5");
    print_dw(data->DelayAfterPCIeLinkTraining, "DelayAfterPCIeLinkTraining");
    print_dd(data->PciBusResConfigPtr, "PciBusResConfigPtr");
    print_dd(data->PciBaseLimitsResConfigPtr, "PciBaseLimitsResConfigPtr");
    print_db(data->PchPciePllSsc, "PchPciePllSsc");
    print_db(data->MeUmaEnable, "MeUmaEnable");
    print_db(data->SerialIoUartDebugEnable, "SerialIoUartDebugEnable");
    print_db(data->UnusedUpdSpace6, "UnusedUpdSpace6");
    print_dw(data->SerialIoUartDebugIoBase, "SerialIoUartDebugIoBase");
    print_db(data->PanicWm, "PanicWm");
    print_db(data->promoteMrcWarnings, "promoteMrcWarnings");
    print_db(data->promoteWarnings, "promoteWarnings");
    print_db(data->serialDebugMsgLvlTrainResults, "serialDebugMsgLvlTrainResults");
    print_db(data->HwMemTest, "HwMemTest");
    print_db(data->UnusedUpdSpace7, "UnusedUpdSpace7");
    print_dw(data->MemTestLoops, "MemTestLoops");
    print_db_array(data->UnusedUpdSpace8, 2, "UnusedUpdSpace8");
    print_dd(data->AdvMemTestOptions, "AdvMemTestOptions");
    print_dd(data->SmartTestKey, "SmartTestKey");
    print_dd(data->AdvMemTestCondPause, "AdvMemTestCondPause");
    print_dw(data->AdvMemTestCondTrefi, "AdvMemTestCondTrefi");
    print_db(data->AdvMemTestCondTwr, "AdvMemTestCondTwr");
    print_db(data->UnusedUpdSpace9, "UnusedUpdSpace9");
    print_dw(data->AdvMemTestCondPmicVdd, "AdvMemTestCondPmicVdd");
    print_db(data->AdvMemTestCondition, "AdvMemTestCondition");
    print_db(data->AdvMemTestResetList, "AdvMemTestResetList");
    print_db(data->MemTestOnColdFastBoot, "MemTestOnColdFastBoot");
    print_db(data->AttemptFastBoot, "AttemptFastBoot");
    print_db(data->AttemptFastBootCold, "AttemptFastBootCold");
    print_db(data->AllowedSocketsInParallel, "AllowedSocketsInParallel");
    print_db(data->AutoResetOnMemErr, "AutoResetOnMemErr");
    print_db(data->EnableRMT, "EnableRMT");
    print_db(data->EnableRMTonFCB, "EnableRMTonFCB");
    print_db(data->JedecInitBeforeRMT, "JedecInitBeforeRMT");
    print_db(data->RMTBacksideMargining, "RMTBacksideMargining");
    print_db(data->RMTCmdAll, "RMTCmdAll");
    print_db(data->RMTDebugMessages, "RMTDebugMessages");
    print_db(data->RMTDisplayTables, "RMTDisplayTables");
    print_db(data->RMTLoopCount, "RMTLoopCount");
    print_db_array(data->UnusedUpdSpace10, 3, "UnusedUpdSpace10");
    print_dd(data->TestSignalBitMaskRMT, "TestSignalBitMaskRMT");
    print_db(data->RMTPerBitMargining, "RMTPerBitMargining");
    print_db(data->RMTPerCaLaneMargining, "RMTPerCaLaneMargining");
    print_db(data->RMTPerDisplayPlots, "RMTPerDisplayPlots");
    print_db(data->RMTRxDqs, "RMTRxDqs");
    print_db(data->RMTRxVref, "RMTRxVref");
    print_db(data->RMTScrambler, "RMTScrambler");
    print_db(data->RMTStepSizeOverride, "RMTStepSizeOverride");
    print_db(data->RMTTxDq, "RMTTxDq");
    print_db(data->RMTTxVref, "RMTTxVref");
    print_db(data->ErrorCheckScrub, "ErrorCheckScrub");
    print_db(data->EnforceDdrMemoryFreqPor, "EnforceDdrMemoryFreqPor");
    print_db(data->EnforcePopulationPor, "EnforcePopulationPor");
    print_db(data->pprType, "pprType");
    print_db(data->ForcePprOnAllDramUce, "ForcePprOnAllDramUce");
    print_db_array(data->UnusedUpdSpace11, 2, "UnusedUpdSpace11");
    print_dd(data->PprAddrVariablePtr, "PprAddrVariablePtr");
    print_db(data->allowCorrectableMemTestError, "allowCorrectableMemTestError");
    print_db(data->MemIOHealthCheck, "MemIOHealthCheck");
    print_db(data->CriticalRxDqsDelayLeftEdge, "CriticalRxDqsDelayLeftEdge");
    print_db(data->CriticalRxDqsDelayRightEdge, "CriticalRxDqsDelayRightEdge");
    print_db(data->CriticalRxVrefLeftEdge, "CriticalRxVrefLeftEdge");
    print_db(data->CriticalRxVrefRightEdge, "CriticalRxVrefRightEdge");
    print_db(data->CriticalTxDqDelayLeftEdge, "CriticalTxDqDelayLeftEdge");
    print_db(data->CriticalTxDqDelayRightEdge, "CriticalTxDqDelayRightEdge");
    print_db(data->CriticalTxVrefLeftEdge, "CriticalTxVrefLeftEdge");
    print_db(data->CriticalTxVrefRightEdge, "CriticalTxVrefRightEdge");
    print_db(data->MemIOHealthCriticalCaTimingLeftEdge, "MemIOHealthCriticalCaTimingLeftEdge");
    print_db(data->MemIOHealthCriticalCaTimingRightEdge, "MemIOHealthCriticalCaTimingRightEdge");
    print_db(data->MemIOHealthCriticalCaVrefLeftEdge, "MemIOHealthCriticalCaVrefLeftEdge");
    print_db(data->MemIOHealthCriticalCaVrefRightEdge, "MemIOHealthCriticalCaVrefRightEdge");
    print_db(data->ResetOnCriticalError, "ResetOnCriticalError");
    print_db(data->CriticalRetries, "CriticalRetries");
    print_db(data->MemIOHealthLoopCount, "MemIOHealthLoopCount");
    print_db(data->TelemetryRxDqsDelayLeftEdge, "TelemetryRxDqsDelayLeftEdge");
    print_db(data->TelemetryRxDqsDelayRightEdge, "TelemetryRxDqsDelayRightEdge");
    print_db(data->TelemetryRxVrefLeftEdge, "TelemetryRxVrefLeftEdge");
    print_db(data->TelemetryRxVrefRightEdge, "TelemetryRxVrefRightEdge");
    print_db(data->TelemetryTxDqDelayLeftEdge, "TelemetryTxDqDelayLeftEdge");
    print_db(data->TelemetryTxDqDelayRightEdge, "TelemetryTxDqDelayRightEdge");
    print_db(data->MemIOHealthTelemetryCaTimingLeftEdge, "MemIOHealthTelemetryCaTimingLeftEdge");
    print_db(data->MemIOHealthTelemetryCaTimingRightEdge, "MemIOHealthTelemetryCaTimingRightEdge");
    print_db(data->MemIOHealthTelemetryCaVrefLeftEdge, "MemIOHealthTelemetryCaVrefLeftEdge");
    print_db(data->MemIOHealthTelemetryCaVrefRightEdge, "MemIOHealthTelemetryCaVrefRightEdge");
    print_db(data->volMemMode, "volMemMode");
    print_db(data->DynamicEccModeSel, "DynamicEccModeSel");
    print_db(data->PatrolScrub, "PatrolScrub");
    print_db(data->PatrolScrubNotify, "PatrolScrubNotify");
    print_db(data->PatrolScrubDuration, "PatrolScrubDuration");
    print_db(data->PatrolScrubAddrMode, "PatrolScrubAddrMode");
    print_db(data->thermalthrottlingsupport, "thermalthrottlingsupport");
    print_dw(data->spareErrTh, "spareErrTh");
    print_db(data->WrCRC, "WrCRC");
    print_db(data->AdaptiveRefreshMgmtLevel, "AdaptiveRefreshMgmtLevel");
    print_db(data->MemHotIn, "MemHotIn");
    print_db(data->MemhotOutputOnlyOpt, "MemhotOutputOnlyOpt");
    print_db(data->DfxCxlType3LegacyEn, "DfxCxlType3LegacyEn");
    print_db(data->DfxPmicSecureMode, "DfxPmicSecureMode");
    print_db_array(data->IioPcieSubSystemMode0, 8, "IioPcieSubSystemMode0");
    print_db_array(data->IioPcieSubSystemMode1, 8, "IioPcieSubSystemMode1");
    print_db_array(data->IioPcieSubSystemMode2, 8, "IioPcieSubSystemMode2");
    print_db_array(data->IioPcieSubSystemMode3, 8, "IioPcieSubSystemMode3");
    print_db_array(data->IioPcieSubSystemMode4, 8, "IioPcieSubSystemMode4");
    print_db_array(data->IioPcieSubSystemMode5, 8, "IioPcieSubSystemMode5");
    print_db_array(data->IioPcieSubSystemMode6, 8, "IioPcieSubSystemMode6");
    print_db(data->DfxCxlHeaderBypass, "DfxCxlHeaderBypass");
    print_db(data->DfxCxlSecLvl, "DfxCxlSecLvl");
    print_dd(data->DfxCxlDebugModePtr, "DfxCxlDebugModePtr");
    print_dd(data->DfxCxlDebugModeNumber, "DfxCxlDebugModeNumber");
    print_db(data->LockChipset, "LockChipset");
    print_db(data->ProcessorMsrLockControl, "ProcessorMsrLockControl");
    print_db(data->DFXEnable, "DFXEnable");
    print_db(data->DfxDisableBiosDone, "DfxDisableBiosDone");
    print_db(data->CpuPmPackageCState, "CpuPmPackageCState");
    print_db(data->CpuPmEistEnable, "CpuPmEistEnable");
    print_db(data->CpuPmC1eEnable, "CpuPmC1eEnable");
    print_db(data->CpuPmIssTdpLevel, "CpuPmIssTdpLevel");
    print_db(data->CpuPmProcessorActivePbf, "CpuPmProcessorActivePbf");
    print_db_array(data->UnusedUpdSpace12, 7, "UnusedUpdSpace12");
    print_dq(data->CpuPmCoreDisableBitmask0, "CpuPmCoreDisableBitmask0");
    print_dq(data->CpuPmCoreDisableBitmask1, "CpuPmCoreDisableBitmask1");
    print_db_array(data->ReservedMemoryInitUpd, 16, "ReservedMemoryInitUpd");
}
